// src/app/quiz/deutschlandQuestions.ts

export interface QuizQuestion {
  question: string;
  options: string[];
  correctAnswer: number; // Index of correct option
  category: 'Geografie' | 'Geschichte' | 'Kultur' | 'Politik' | 'Sport' | 'Wirtschaft';
  difficulty: 'easy' | 'medium' | 'hard';
}

export const deutschlandQuestions: QuizQuestion[] = [
  // GEOGRAFIE - Easy
  {
    question: 'Wie heißt die Hauptstadt von Deutschland?',
    options: ['München', 'Berlin', 'Hamburg', 'Frankfurt'],
    correctAnswer: 1,
    category: 'Geografie',
    difficulty: 'easy',
  },
  {
    question: 'Welcher ist der längste Fluss Deutschlands?',
    options: ['Donau', 'Elbe', 'Weser', 'Rhein'],
    correctAnswer: 3,
    category: 'Geografie',
    difficulty: 'easy',
  },
  {
    question: 'Wie viele Bundesländer hat Deutschland?',
    options: ['12', '14', '16', '18'],
    correctAnswer: 2,
    category: 'Geografie',
    difficulty: 'easy',
  },
  {
    question: 'Welches Bundesland ist flächenmäßig das größte?',
    options: ['Bayern', 'Niedersachsen', 'Baden-Württemberg', 'Nordrhein-Westfalen'],
    correctAnswer: 0,
    category: 'Geografie',
    difficulty: 'easy',
  },
  {
    question: 'An wie viele Länder grenzt Deutschland?',
    options: ['7', '9', '11', '13'],
    correctAnswer: 1,
    category: 'Geografie',
    difficulty: 'easy',
  },
  {
    question: 'Welche Stadt hat die meisten Einwohner?',
    options: ['Hamburg', 'München', 'Berlin', 'Köln'],
    correctAnswer: 2,
    category: 'Geografie',
    difficulty: 'easy',
  },
  {
    question: 'Welcher Berg ist der höchste in Deutschland?',
    options: ['Watzmann', 'Feldberg', 'Zugspitze', 'Brocken'],
    correctAnswer: 2,
    category: 'Geografie',
    difficulty: 'easy',
  },
  {
    question: 'Welches Meer grenzt im Norden an Deutschland?',
    options: ['Ostsee', 'Mittelmeer', 'Atlantik', 'Schwarzes Meer'],
    correctAnswer: 0,
    category: 'Geografie',
    difficulty: 'easy',
  },
  {
    question: 'In welchem Bundesland liegt München?',
    options: ['Baden-Württemberg', 'Bayern', 'Hessen', 'Sachsen'],
    correctAnswer: 1,
    category: 'Geografie',
    difficulty: 'easy',
  },
  {
    question: 'Welche Stadt liegt am Rhein?',
    options: ['Dresden', 'Leipzig', 'Köln', 'Erfurt'],
    correctAnswer: 2,
    category: 'Geografie',
    difficulty: 'easy',
  },

  // GEOGRAFIE - Medium
  {
    question: 'Welcher See ist der größte in Deutschland?',
    options: ['Bodensee', 'Chiemsee', 'Müritz', 'Starnberger See'],
    correctAnswer: 0,
    category: 'Geografie',
    difficulty: 'medium',
  },
  {
    question: 'Wie heißt die Hauptstadt von Bayern?',
    options: ['Nürnberg', 'Augsburg', 'München', 'Regensburg'],
    correctAnswer: 2,
    category: 'Geografie',
    difficulty: 'medium',
  },
  {
    question: 'Welches Bundesland hat die wenigsten Einwohner?',
    options: ['Saarland', 'Bremen', 'Mecklenburg-Vorpommern', 'Thüringen'],
    correctAnswer: 1,
    category: 'Geografie',
    difficulty: 'medium',
  },
  {
    question: 'In welchem Bundesland liegt der Schwarzwald?',
    options: ['Bayern', 'Hessen', 'Baden-Württemberg', 'Rheinland-Pfalz'],
    correctAnswer: 2,
    category: 'Geografie',
    difficulty: 'medium',
  },
  {
    question: 'Welche Stadt ist die Hauptstadt von Sachsen?',
    options: ['Leipzig', 'Dresden', 'Chemnitz', 'Zwickau'],
    correctAnswer: 1,
    category: 'Geografie',
    difficulty: 'medium',
  },
  {
    question: 'Wo liegt die Insel Rügen?',
    options: ['Nordsee', 'Ostsee', 'Bodensee', 'Chiemsee'],
    correctAnswer: 1,
    category: 'Geografie',
    difficulty: 'medium',
  },
  {
    question: 'Welcher Fluss fließt durch Hamburg?',
    options: ['Rhein', 'Elbe', 'Weser', 'Spree'],
    correctAnswer: 1,
    category: 'Geografie',
    difficulty: 'medium',
  },
  {
    question: 'Wie heißt die Hauptstadt von Nordrhein-Westfalen?',
    options: ['Köln', 'Dortmund', 'Düsseldorf', 'Essen'],
    correctAnswer: 2,
    category: 'Geografie',
    difficulty: 'medium',
  },
  {
    question: 'In welchem Bundesland liegt Frankfurt am Main?',
    options: ['Bayern', 'Hessen', 'Baden-Württemberg', 'Rheinland-Pfalz'],
    correctAnswer: 1,
    category: 'Geografie',
    difficulty: 'medium',
  },
  {
    question: 'Welches Bundesland ist eine Enklave?',
    options: ['Saarland', 'Bremen', 'Berlin', 'Hamburg'],
    correctAnswer: 1,
    category: 'Geografie',
    difficulty: 'medium',
  },

  // GEOGRAFIE - Hard
  {
    question: 'Wie viele Kilometer Küste hat Deutschland?',
    options: ['ca. 1.200 km', 'ca. 2.400 km', 'ca. 3.800 km', 'ca. 5.000 km'],
    correctAnswer: 2,
    category: 'Geografie',
    difficulty: 'hard',
  },
  {
    question: 'Welcher Fluss bildet teilweise die Grenze zu Polen?',
    options: ['Oder', 'Elbe', 'Neiße', 'Both A and C'],
    correctAnswer: 3,
    category: 'Geografie',
    difficulty: 'hard',
  },
  {
    question: 'Wie heißt der höchste Berg im Harz?',
    options: ['Feldberg', 'Brocken', 'Fichtelberg', 'Arber'],
    correctAnswer: 1,
    category: 'Geografie',
    difficulty: 'hard',
  },
  {
    question: 'Welche Stadt liegt am weitesten nördlich?',
    options: ['Flensburg', 'Kiel', 'Lübeck', 'Rostock'],
    correctAnswer: 0,
    category: 'Geografie',
    difficulty: 'hard',
  },
  {
    question: 'Wie viele Inseln gehören zu den Ostfriesischen Inseln?',
    options: ['5', '7', '9', '11'],
    correctAnswer: 1,
    category: 'Geografie',
    difficulty: 'hard',
  },

  // GESCHICHTE - Easy
  {
    question: 'Wann fiel die Berliner Mauer?',
    options: ['1987', '1989', '1991', '1993'],
    correctAnswer: 1,
    category: 'Geschichte',
    difficulty: 'easy',
  },
  {
    question: 'Wer war der erste Bundeskanzler?',
    options: ['Willy Brandt', 'Helmut Schmidt', 'Konrad Adenauer', 'Ludwig Erhard'],
    correctAnswer: 2,
    category: 'Geschichte',
    difficulty: 'easy',
  },
  {
    question: 'In welchem Jahr wurde Deutschland wiedervereinigt?',
    options: ['1989', '1990', '1991', '1992'],
    correctAnswer: 1,
    category: 'Geschichte',
    difficulty: 'easy',
  },
  {
    question: 'Wann endete der Zweite Weltkrieg?',
    options: ['1943', '1944', '1945', '1946'],
    correctAnswer: 2,
    category: 'Geschichte',
    difficulty: 'easy',
  },
  {
    question: 'Welches Jahr markiert das Ende des Deutschen Kaiserreichs?',
    options: ['1914', '1916', '1918', '1920'],
    correctAnswer: 2,
    category: 'Geschichte',
    difficulty: 'easy',
  },
  {
    question: 'Wer war der letzte Kaiser Deutschlands?',
    options: ['Wilhelm I', 'Wilhelm II', 'Friedrich III', 'Otto von Bismarck'],
    correctAnswer: 1,
    category: 'Geschichte',
    difficulty: 'easy',
  },
  {
    question: 'Wann wurde die BRD gegründet?',
    options: ['1947', '1948', '1949', '1950'],
    correctAnswer: 2,
    category: 'Geschichte',
    difficulty: 'easy',
  },
  {
    question: 'In welchem Jahr begann der Erste Weltkrieg?',
    options: ['1912', '1914', '1916', '1918'],
    correctAnswer: 1,
    category: 'Geschichte',
    difficulty: 'easy',
  },
  {
    question: 'Wer war Bundeskanzler während der Wiedervereinigung?',
    options: ['Helmut Schmidt', 'Helmut Kohl', 'Gerhard Schröder', 'Angela Merkel'],
    correctAnswer: 1,
    category: 'Geschichte',
    difficulty: 'easy',
  },
  {
    question: 'Wie hieß Deutschland vor 1871?',
    options: ['Deutsches Reich', 'Deutscher Bund', 'Heiliges Römisches Reich', 'Preußen'],
    correctAnswer: 1,
    category: 'Geschichte',
    difficulty: 'easy',
  },

  // GESCHICHTE - Medium
  {
    question: 'Wann wurde die DDR gegründet?',
    options: ['1947', '1948', '1949', '1950'],
    correctAnswer: 2,
    category: 'Geschichte',
    difficulty: 'medium',
  },
  {
    question: 'Wer war der zweite Bundeskanzler der BRD?',
    options: ['Ludwig Erhard', 'Willy Brandt', 'Kurt Georg Kiesinger', 'Helmut Schmidt'],
    correctAnswer: 0,
    category: 'Geschichte',
    difficulty: 'medium',
  },
  {
    question: 'In welchem Jahr wurde das Grundgesetz verabschiedet?',
    options: ['1947', '1948', '1949', '1950'],
    correctAnswer: 2,
    category: 'Geschichte',
    difficulty: 'medium',
  },
  {
    question: 'Wann begann die Weimarer Republik?',
    options: ['1918', '1919', '1920', '1921'],
    correctAnswer: 1,
    category: 'Geschichte',
    difficulty: 'medium',
  },
  {
    question: 'Wer war der erste Bundespräsident der BRD?',
    options: ['Theodor Heuss', 'Heinrich Lübke', 'Gustav Heinemann', 'Walter Scheel'],
    correctAnswer: 0,
    category: 'Geschichte',
    difficulty: 'medium',
  },
  {
    question: 'In welchem Jahr trat Deutschland der NATO bei?',
    options: ['1949', '1951', '1955', '1957'],
    correctAnswer: 2,
    category: 'Geschichte',
    difficulty: 'medium',
  },
  {
    question: 'Wann wurde die Deutsche Mark eingeführt?',
    options: ['1946', '1948', '1949', '1950'],
    correctAnswer: 1,
    category: 'Geschichte',
    difficulty: 'medium',
  },
  {
    question: 'Wer war der längste amtierende Bundeskanzler?',
    options: ['Konrad Adenauer', 'Helmut Kohl', 'Angela Merkel', 'Helmut Schmidt'],
    correctAnswer: 2,
    category: 'Geschichte',
    difficulty: 'medium',
  },
  {
    question: 'In welchem Jahr wurde die Mauer gebaut?',
    options: ['1959', '1961', '1963', '1965'],
    correctAnswer: 1,
    category: 'Geschichte',
    difficulty: 'medium',
  },
  {
    question: 'Wann trat der Euro in Deutschland in Kraft?',
    options: ['1999', '2000', '2001', '2002'],
    correctAnswer: 3,
    category: 'Geschichte',
    difficulty: 'medium',
  },

  // GESCHICHTE - Hard
  {
    question: 'Wann wurde Otto von Bismarck Reichskanzler?',
    options: ['1862', '1871', '1878', '1882'],
    correctAnswer: 1,
    category: 'Geschichte',
    difficulty: 'hard',
  },
  {
    question: 'In welchem Jahr endete die Weimarer Republik?',
    options: ['1931', '1932', '1933', '1934'],
    correctAnswer: 2,
    category: 'Geschichte',
    difficulty: 'hard',
  },
  {
    question: 'Wann wurde der Zwei-plus-Vier-Vertrag unterzeichnet?',
    options: ['1989', '1990', '1991', '1992'],
    correctAnswer: 1,
    category: 'Geschichte',
    difficulty: 'hard',
  },
  {
    question: 'Wer war Reichspräsident vor Paul von Hindenburg?',
    options: ['Friedrich Ebert', 'Gustav Stresemann', 'Philipp Scheidemann', 'Wilhelm Marx'],
    correctAnswer: 0,
    category: 'Geschichte',
    difficulty: 'hard',
  },
  {
    question: 'In welchem Jahr fand die Deutsche Revolution statt?',
    options: ['1848', '1918', '1989', 'Both A and B'],
    correctAnswer: 3,
    category: 'Geschichte',
    difficulty: 'hard',
  },

  // KULTUR - Easy
  {
    question: 'Welches Fest wird in München gefeiert?',
    options: ['Karneval', 'Oktoberfest', 'Weinfest', 'Schützenfest'],
    correctAnswer: 1,
    category: 'Kultur',
    difficulty: 'easy',
  },
  {
    question: 'Wer schrieb "Faust"?',
    options: ['Schiller', 'Goethe', 'Heine', 'Brecht'],
    correctAnswer: 1,
    category: 'Kultur',
    difficulty: 'easy',
  },
  {
    question: 'Welches Instrument erfand Johann Sebastian Bach nicht?',
    options: ['Orgel', 'Klavier', 'Cembalo', 'Er erfand keins'],
    correctAnswer: 3,
    category: 'Kultur',
    difficulty: 'easy',
  },
  {
    question: 'Was ist das Brandenburger Tor?',
    options: ['Kirche', 'Museum', 'Tor', 'Rathaus'],
    correctAnswer: 2,
    category: 'Kultur',
    difficulty: 'easy',
  },
  {
    question: 'In welcher Stadt steht der Kölner Dom?',
    options: ['Berlin', 'München', 'Köln', 'Hamburg'],
    correctAnswer: 2,
    category: 'Kultur',
    difficulty: 'easy',
  },
  {
    question: 'Welcher Komponist schrieb die 9. Sinfonie?',
    options: ['Mozart', 'Bach', 'Beethoven', 'Wagner'],
    correctAnswer: 2,
    category: 'Kultur',
    difficulty: 'easy',
  },
  {
    question: 'Was ist ein typisches deutsches Gericht?',
    options: ['Pizza', 'Sushi', 'Bratwurst', 'Tacos'],
    correctAnswer: 2,
    category: 'Kultur',
    difficulty: 'easy',
  },
  {
    question: 'Welches Märchen schrieben die Brüder Grimm?',
    options: ['Die Schneekönigin', 'Rotkäppchen', 'Die kleine Meerjungfrau', 'Pinocchio'],
    correctAnswer: 1,
    category: 'Kultur',
    difficulty: 'easy',
  },
  {
    question: 'Welches UNESCO-Welterbe liegt in Deutschland?',
    options: ['Eiffelturm', 'Kölner Dom', 'Big Ben', 'Kolosseum'],
    correctAnswer: 1,
    category: 'Kultur',
    difficulty: 'easy',
  },
  {
    question: 'Welcher Weihnachtsmarkt ist weltberühmt?',
    options: [
      'Nürnberger Christkindlesmarkt',
      'Pariser Markt',
      'Londoner Markt',
      'New Yorker Markt',
    ],
    correctAnswer: 0,
    category: 'Kultur',
    difficulty: 'easy',
  },

  // KULTUR - Medium
  {
    question: 'Wer komponierte "Die Zauberflöte"?',
    options: ['Bach', 'Beethoven', 'Mozart', 'Wagner'],
    correctAnswer: 2,
    category: 'Kultur',
    difficulty: 'medium',
  },
  {
    question: 'In welcher Stadt wurde Goethe geboren?',
    options: ['Weimar', 'Frankfurt', 'Leipzig', 'Berlin'],
    correctAnswer: 1,
    category: 'Kultur',
    difficulty: 'medium',
  },
  {
    question: 'Welches Museum liegt auf der Museumsinsel in Berlin?',
    options: ['Louvre', 'Pergamonmuseum', 'MoMA', 'Prado'],
    correctAnswer: 1,
    category: 'Kultur',
    difficulty: 'medium',
  },
  {
    question: 'Wer schrieb "Die Räuber"?',
    options: ['Goethe', 'Schiller', 'Lessing', 'Heine'],
    correctAnswer: 1,
    category: 'Kultur',
    difficulty: 'medium',
  },
  {
    question: 'Welches Schloss liegt in Bayern?',
    options: ['Sanssouci', 'Neuschwanstein', 'Versailles', 'Schönbrunn'],
    correctAnswer: 1,
    category: 'Kultur',
    difficulty: 'medium',
  },
  {
    question: 'Wer malte "Der Wanderer über dem Nebelmeer"?',
    options: ['Dürer', 'Cranach', 'Friedrich', 'Holbein'],
    correctAnswer: 2,
    category: 'Kultur',
    difficulty: 'medium',
  },
  {
    question: 'Welche Oper schrieb Richard Wagner?',
    options: ['Carmen', 'Die Walküre', 'La Traviata', 'Tosca'],
    correctAnswer: 1,
    category: 'Kultur',
    difficulty: 'medium',
  },
  {
    question: 'Was ist die Berlinale?',
    options: ['Marathon', 'Filmfestival', 'Volksfest', 'Konzert'],
    correctAnswer: 1,
    category: 'Kultur',
    difficulty: 'medium',
  },
  {
    question: 'Wer schrieb "Im Westen nichts Neues"?',
    options: ['Thomas Mann', 'Erich Maria Remarque', 'Heinrich Böll', 'Günter Grass'],
    correctAnswer: 1,
    category: 'Kultur',
    difficulty: 'medium',
  },
  {
    question: 'Welcher Stil prägt den Kölner Dom?',
    options: ['Romanik', 'Gotik', 'Barock', 'Klassizismus'],
    correctAnswer: 1,
    category: 'Kultur',
    difficulty: 'medium',
  },

  // KULTUR - Hard
  {
    question: 'Wer erhielt 1999 den Literaturnobelpreis?',
    options: ['Günter Grass', 'Heinrich Böll', 'Thomas Mann', 'Hermann Hesse'],
    correctAnswer: 0,
    category: 'Kultur',
    difficulty: 'hard',
  },
  {
    question: 'Welches Bauhaus gründete Walter Gropius?',
    options: ['Berlin Bauhaus', 'Weimarer Bauhaus', 'München Bauhaus', 'Dresden Bauhaus'],
    correctAnswer: 1,
    category: 'Kultur',
    difficulty: 'hard',
  },
  {
    question: 'Wer schrieb "Der Steppenwolf"?',
    options: ['Thomas Mann', 'Hermann Hesse', 'Robert Musil', 'Franz Kafka'],
    correctAnswer: 1,
    category: 'Kultur',
    difficulty: 'hard',
  },
  {
    question: 'In welchem Jahr wurde die Elbphilharmonie eröffnet?',
    options: ['2015', '2016', '2017', '2018'],
    correctAnswer: 2,
    category: 'Kultur',
    difficulty: 'hard',
  },
  {
    question: 'Wer komponierte den "Ring des Nibelungen"?',
    options: ['Brahms', 'Wagner', 'Strauss', 'Mahler'],
    correctAnswer: 1,
    category: 'Kultur',
    difficulty: 'hard',
  },

  // POLITIK - Easy
  {
    question: 'Wie heißt die deutsche Bundeskanzlerin seit 2021?',
    options: ['Angela Merkel', 'Annalena Baerbock', 'Es gibt keine', 'Keine dieser Optionen'],
    correctAnswer: 2,
    category: 'Politik',
    difficulty: 'easy',
  },
  {
    question: 'Wie viele Sitze hat der Bundestag mindestens?',
    options: ['598', '630', '709', 'Variable'],
    correctAnswer: 0,
    category: 'Politik',
    difficulty: 'easy',
  },
  {
    question: 'Wer wählt den Bundeskanzler?',
    options: ['Das Volk', 'Der Bundestag', 'Der Bundesrat', 'Der Bundespräsident'],
    correctAnswer: 1,
    category: 'Politik',
    difficulty: 'easy',
  },
  {
    question: 'Wie heißt das deutsche Parlament?',
    options: ['Reichstag', 'Bundestag', 'Landtag', 'Senat'],
    correctAnswer: 1,
    category: 'Politik',
    difficulty: 'easy',
  },
  {
    question: 'Wer ist das Staatsoberhaupt Deutschlands?',
    options: ['Bundeskanzler', 'Bundespräsident', 'Bundesminister', 'EU-Präsident'],
    correctAnswer: 1,
    category: 'Politik',
    difficulty: 'easy',
  },
  {
    question: 'Ab welchem Alter darf man in Deutschland wählen?',
    options: ['16', '18', '21', '25'],
    correctAnswer: 1,
    category: 'Politik',
    difficulty: 'easy',
  },
  {
    question: 'Welche Farben hat die deutsche Flagge?',
    options: ['Schwarz-Rot-Gold', 'Schwarz-Weiß-Rot', 'Rot-Weiß-Blau', 'Blau-Gelb-Rot'],
    correctAnswer: 0,
    category: 'Politik',
    difficulty: 'easy',
  },
  {
    question: 'Wo tagt der Bundestag?',
    options: ['Bonn', 'Berlin', 'Frankfurt', 'München'],
    correctAnswer: 1,
    category: 'Politik',
    difficulty: 'easy',
  },
  {
    question: 'Wie oft wird der Bundestag gewählt?',
    options: ['Alle 3 Jahre', 'Alle 4 Jahre', 'Alle 5 Jahre', 'Alle 6 Jahre'],
    correctAnswer: 1,
    category: 'Politik',
    difficulty: 'easy',
  },
  {
    question: 'Was ist die 5%-Hürde?',
    options: ['Wahlbeteiligung', 'Sperrklausel', 'Steuersatz', 'Inflationsrate'],
    correctAnswer: 1,
    category: 'Politik',
    difficulty: 'easy',
  },

  // POLITIK - Medium
  {
    question: 'Wie viele Stimmen hat jeder Wähler bei der Bundestagswahl?',
    options: ['1', '2', '3', '4'],
    correctAnswer: 1,
    category: 'Politik',
    difficulty: 'medium',
  },
  {
    question: 'Wer ernennt die Bundesminister?',
    options: ['Bundestag', 'Bundeskanzler', 'Bundespräsident', 'Bundesrat'],
    correctAnswer: 2,
    category: 'Politik',
    difficulty: 'medium',
  },
  {
    question: 'Aus wie vielen Mitgliedern besteht die Bundesversammlung?',
    options: ['Variiert', '1000', '1500', '2000'],
    correctAnswer: 0,
    category: 'Politik',
    difficulty: 'medium',
  },
  {
    question: 'Welches Gericht ist das höchste in Deutschland?',
    options: ['BGH', 'BVerfG', 'EuGH', 'OLG'],
    correctAnswer: 1,
    category: 'Politik',
    difficulty: 'medium',
  },
  {
    question: 'Wo hat das Bundesverfassungsgericht seinen Sitz?',
    options: ['Berlin', 'Bonn', 'Karlsruhe', 'München'],
    correctAnswer: 2,
    category: 'Politik',
    difficulty: 'medium',
  },
  {
    question: 'Wie lange ist die Amtszeit des Bundespräsidenten?',
    options: ['4 Jahre', '5 Jahre', '6 Jahre', '8 Jahre'],
    correctAnswer: 1,
    category: 'Politik',
    difficulty: 'medium',
  },
  {
    question: 'Wer vertritt die Bundesländer auf Bundesebene?',
    options: ['Bundestag', 'Bundesrat', 'Landtag', 'Bundesversammlung'],
    correctAnswer: 1,
    category: 'Politik',
    difficulty: 'medium',
  },
  {
    question: 'Welches Wahlsystem hat Deutschland?',
    options: [
      'Mehrheitswahlrecht',
      'Verhältniswahlrecht',
      'Personalisiertes Verhältniswahlrecht',
      'Direktwahl',
    ],
    correctAnswer: 2,
    category: 'Politik',
    difficulty: 'medium',
  },
  {
    question: 'Wann wurde das Grundgesetz zuletzt geändert?',
    options: ['2020', '2021', '2022', 'Wird laufend geändert'],
    correctAnswer: 3,
    category: 'Politik',
    difficulty: 'medium',
  },
  {
    question: 'Was bedeutet das föderale Prinzip?',
    options: ['Demokratie', 'Gewaltenteilung', 'Länderautonomie', 'Rechtsstaat'],
    correctAnswer: 2,
    category: 'Politik',
    difficulty: 'medium',
  },

  // POLITIK - Hard
  {
    question: 'Wie viele Artikel hat das Grundgesetz?',
    options: ['146', '183', '209', 'Variiert'],
    correctAnswer: 0,
    category: 'Politik',
    difficulty: 'hard',
  },
  {
    question: 'Wann trat Deutschland der EU bei?',
    options: ['1957', '1973', '1992', 'Gründungsmitglied'],
    correctAnswer: 3,
    category: 'Politik',
    difficulty: 'hard',
  },
  {
    question: 'Wie heißt der längste Artikel im Grundgesetz?',
    options: ['Art. 1', 'Art. 20', 'Art. 74', 'Art. 146'],
    correctAnswer: 2,
    category: 'Politik',
    difficulty: 'hard',
  },
  {
    question: 'Wer kann den Bundespräsidenten anklagen?',
    options: ['Bundestag', 'Bundesrat', 'Both A and B', 'Bundesverfassungsgericht'],
    correctAnswer: 2,
    category: 'Politik',
    difficulty: 'hard',
  },
  {
    question: 'Was ist die Ewigkeitsklausel?',
    options: ['Art. 1', 'Art. 20', 'Art. 79 Abs. 3', 'Art. 146'],
    correctAnswer: 2,
    category: 'Politik',
    difficulty: 'hard',
  },

  // SPORT - Easy
  {
    question: 'Welcher Verein gewann die meisten deutschen Meisterschaften?',
    options: ['Borussia Dortmund', 'Bayern München', 'Schalke 04', 'Werder Bremen'],
    correctAnswer: 1,
    category: 'Sport',
    difficulty: 'easy',
  },
  {
    question: 'In welchem Jahr gewann Deutschland die WM in Brasilien?',
    options: ['2010', '2012', '2014', '2016'],
    correctAnswer: 2,
    category: 'Sport',
    difficulty: 'easy',
  },
  {
    question: 'Wer ist der erfolgreichste deutsche Formel-1-Fahrer?',
    options: ['Sebastian Vettel', 'Nico Rosberg', 'Michael Schumacher', 'Ralf Schumacher'],
    correctAnswer: 2,
    category: 'Sport',
    difficulty: 'easy',
  },
  {
    question: 'In welcher Stadt hat der FC Bayern seinen Sitz?',
    options: ['Berlin', 'München', 'Hamburg', 'Köln'],
    correctAnswer: 1,
    category: 'Sport',
    difficulty: 'easy',
  },
  {
    question: 'Wie oft gewann Deutschland die Fußball-WM?',
    options: ['2', '3', '4', '5'],
    correctAnswer: 2,
    category: 'Sport',
    difficulty: 'easy',
  },
  {
    question: 'Welcher Sport wird beim Biathlon kombiniert?',
    options: [
      'Laufen und Schwimmen',
      'Skifahren und Schießen',
      'Radfahren und Laufen',
      'Rudern und Laufen',
    ],
    correctAnswer: 1,
    category: 'Sport',
    difficulty: 'easy',
  },
  {
    question: 'Wer war deutscher Nationaltrainer bei der WM 2014?',
    options: ['Jürgen Klinsmann', 'Joachim Löw', 'Hansi Flick', 'Rudi Völler'],
    correctAnswer: 1,
    category: 'Sport',
    difficulty: 'easy',
  },
  {
    question: 'In welcher Stadt fanden 1972 die Olympischen Spiele statt?',
    options: ['Berlin', 'München', 'Hamburg', 'Köln'],
    correctAnswer: 1,
    category: 'Sport',
    difficulty: 'easy',
  },
  {
    question: 'Welcher deutsche Tennisspieler gewann Wimbledon?',
    options: ['Boris Becker', 'Alexander Zverev', 'Tommy Haas', 'Philipp Kohlschreiber'],
    correctAnswer: 0,
    category: 'Sport',
    difficulty: 'easy',
  },
  {
    question: 'Was ist die Bundesliga?',
    options: ['Basketball-Liga', 'Fußball-Liga', 'Eishockey-Liga', 'Handball-Liga'],
    correctAnswer: 1,
    category: 'Sport',
    difficulty: 'easy',
  },

  // SPORT - Medium
  {
    question: 'Wer schoss das Golden Goal im WM-Finale 2014?',
    options: ['Thomas Müller', 'Mario Götze', 'Lukas Podolski', 'Miroslav Klose'],
    correctAnswer: 1,
    category: 'Sport',
    difficulty: 'medium',
  },
  {
    question: 'Welcher Verein hat die meisten DFB-Pokalsiege?',
    options: ['Bayern München', 'Borussia Dortmund', 'Werder Bremen', 'Schalke 04'],
    correctAnswer: 0,
    category: 'Sport',
    difficulty: 'medium',
  },
  {
    question: 'In welchem Jahr wurde die Bundesliga gegründet?',
    options: ['1960', '1963', '1965', '1968'],
    correctAnswer: 1,
    category: 'Sport',
    difficulty: 'medium',
  },
  {
    question: 'Wer ist Rekordtorschütze der deutschen Nationalmannschaft?',
    options: ['Gerd Müller', 'Miroslav Klose', 'Rudi Völler', 'Jürgen Klinsmann'],
    correctAnswer: 1,
    category: 'Sport',
    difficulty: 'medium',
  },
  {
    question: 'Welches deutsche Team gewann die Champions League 2013?',
    options: ['Borussia Dortmund', 'Bayern München', 'Schalke 04', 'Bayer Leverkusen'],
    correctAnswer: 1,
    category: 'Sport',
    difficulty: 'medium',
  },
  {
    question: 'Wer war der erste deutsche Weltmeister in der Formel 1?',
    options: ['Michael Schumacher', 'Sebastian Vettel', 'Nico Rosberg', 'Keiner'],
    correctAnswer: 0,
    category: 'Sport',
    difficulty: 'medium',
  },
  {
    question: 'In welcher Stadt spielt Borussia Dortmund?',
    options: ['Dortmund', 'Mönchengladbach', 'Duisburg', 'Essen'],
    correctAnswer: 0,
    category: 'Sport',
    difficulty: 'medium',
  },
  {
    question: 'Welcher deutsche Boxer wurde Weltmeister?',
    options: ['Henry Maske', 'Axel Schulz', 'Vitali Klitschko', 'Alle genannten'],
    correctAnswer: 3,
    category: 'Sport',
    difficulty: 'medium',
  },
  {
    question: 'Wie heißt das Stadion des FC Bayern?',
    options: ['Allianz Arena', 'Signal Iduna Park', 'Olympiastadion', 'Mercedes-Benz Arena'],
    correctAnswer: 0,
    category: 'Sport',
    difficulty: 'medium',
  },
  {
    question: 'Wer gewann die Handball-WM 2007?',
    options: ['Frankreich', 'Spanien', 'Deutschland', 'Dänemark'],
    correctAnswer: 2,
    category: 'Sport',
    difficulty: 'medium',
  },

  // SPORT - Hard
  {
    question: 'Wer war 1954 Trainer der deutschen Fußball-Nationalmannschaft?',
    options: ['Sepp Herberger', 'Helmut Schön', 'Jupp Derwall', 'Franz Beckenbauer'],
    correctAnswer: 0,
    category: 'Sport',
    difficulty: 'hard',
  },
  {
    question: 'Wie viele Olympische Goldmedaillen gewann Birgit Fischer?',
    options: ['6', '7', '8', '9'],
    correctAnswer: 2,
    category: 'Sport',
    difficulty: 'hard',
  },
  {
    question: 'Welcher Verein wurde 1900 gegründet?',
    options: ['Bayern München', '1. FC Nürnberg', 'FC Schalke 04', 'Hertha BSC'],
    correctAnswer: 0,
    category: 'Sport',
    difficulty: 'hard',
  },
  {
    question: 'Wann gewann Steffi Graf den Golden Slam?',
    options: ['1987', '1988', '1989', '1990'],
    correctAnswer: 1,
    category: 'Sport',
    difficulty: 'hard',
  },
  {
    question: 'Wie viele Weltmeistertitel holte Michael Schumacher?',
    options: ['5', '6', '7', '8'],
    correctAnswer: 2,
    category: 'Sport',
    difficulty: 'hard',
  },

  // WIRTSCHAFT - Easy
  {
    question: 'Was ist die Währung in Deutschland?',
    options: ['Mark', 'Euro', 'Dollar', 'Pfund'],
    correctAnswer: 1,
    category: 'Wirtschaft',
    difficulty: 'easy',
  },
  {
    question: 'Welche Automarke kommt aus Deutschland?',
    options: ['Ford', 'Toyota', 'BMW', 'Fiat'],
    correctAnswer: 2,
    category: 'Wirtschaft',
    difficulty: 'easy',
  },
  {
    question: 'In welcher Stadt hat die Deutsche Börse ihren Sitz?',
    options: ['Berlin', 'München', 'Frankfurt', 'Hamburg'],
    correctAnswer: 2,
    category: 'Wirtschaft',
    difficulty: 'easy',
  },
  {
    question: 'Was ist der DAX?',
    options: ['Steuer', 'Aktienindex', 'Gesetz', 'Währung'],
    correctAnswer: 1,
    category: 'Wirtschaft',
    difficulty: 'easy',
  },
  {
    question: 'Welches Unternehmen produziert den Golf?',
    options: ['BMW', 'Mercedes', 'Volkswagen', 'Audi'],
    correctAnswer: 2,
    category: 'Wirtschaft',
    difficulty: 'easy',
  },
  {
    question: 'Wo hat Siemens seinen Hauptsitz?',
    options: ['Berlin', 'München', 'Hamburg', 'Frankfurt'],
    correctAnswer: 1,
    category: 'Wirtschaft',
    difficulty: 'easy',
  },
  {
    question: 'Was produziert Adidas?',
    options: ['Autos', 'Sportartikel', 'Möbel', 'Elektronik'],
    correctAnswer: 1,
    category: 'Wirtschaft',
    difficulty: 'easy',
  },
  {
    question: 'Welche Bank heißt Deutsche Bank?',
    options: ['Sparkasse', 'Commerzbank', 'Deutsche Bank', 'DZ Bank'],
    correctAnswer: 2,
    category: 'Wirtschaft',
    difficulty: 'easy',
  },
  {
    question: 'Was verkauft Aldi?',
    options: ['Autos', 'Lebensmittel', 'Möbel', 'Kleidung'],
    correctAnswer: 1,
    category: 'Wirtschaft',
    difficulty: 'easy',
  },
  {
    question: 'Wo hat die Lufthansa ihren Sitz?',
    options: ['Berlin', 'München', 'Frankfurt', 'Köln'],
    correctAnswer: 3,
    category: 'Wirtschaft',
    difficulty: 'easy',
  },

  // WIRTSCHAFT - Medium
  {
    question: 'Wie viele Unternehmen sind im DAX gelistet?',
    options: ['30', '40', '50', '60'],
    correctAnswer: 1,
    category: 'Wirtschaft',
    difficulty: 'medium',
  },
  {
    question: 'Welches Unternehmen ist NICHT im DAX?',
    options: ['SAP', 'Siemens', 'Telekom', 'Aldi'],
    correctAnswer: 3,
    category: 'Wirtschaft',
    difficulty: 'medium',
  },
  {
    question: 'Wer gründete das Unternehmen Bosch?',
    options: ['Carl Benz', 'Robert Bosch', 'Gottlieb Daimler', 'Ferdinand Porsche'],
    correctAnswer: 1,
    category: 'Wirtschaft',
    difficulty: 'medium',
  },
  {
    question: 'In welchem Jahr wurde der Euro eingeführt?',
    options: ['1999', '2000', '2001', '2002'],
    correctAnswer: 3,
    category: 'Wirtschaft',
    difficulty: 'medium',
  },
  {
    question: 'Was ist die BASF?',
    options: ['Bank', 'Chemiekonzern', 'Autokonzern', 'Einzelhandel'],
    correctAnswer: 1,
    category: 'Wirtschaft',
    difficulty: 'medium',
  },
  {
    question: 'Wo hat BMW seinen Hauptsitz?',
    options: ['Berlin', 'München', 'Stuttgart', 'Wolfsburg'],
    correctAnswer: 1,
    category: 'Wirtschaft',
    difficulty: 'medium',
  },
  {
    question: 'Was bedeutet GmbH?',
    options: [
      'Gesellschaft mit beschränkter Haftung',
      'Gemeinsam mit besserer Hoffnung',
      'Großer Mittelständischer Betrieb',
      'Gesetzliche Monopol Behörde',
    ],
    correctAnswer: 0,
    category: 'Wirtschaft',
    difficulty: 'medium',
  },
  {
    question: 'Welches Unternehmen produziert den Porsche?',
    options: ['Volkswagen-Konzern', 'BMW', 'Daimler', 'Unabhängig'],
    correctAnswer: 0,
    category: 'Wirtschaft',
    difficulty: 'medium',
  },
  {
    question: 'Was ist die EZB?',
    options: [
      'Europäische Zentralbank',
      'Europäische Zentral Behörde',
      'Einheits Zentral Bank',
      'Export Zentral Büro',
    ],
    correctAnswer: 0,
    category: 'Wirtschaft',
    difficulty: 'medium',
  },
  {
    question: 'Wo hat Porsche seinen Sitz?',
    options: ['München', 'Stuttgart', 'Wolfsburg', 'Ingolstadt'],
    correctAnswer: 1,
    category: 'Wirtschaft',
    difficulty: 'medium',
  },

  // WIRTSCHAFT - Hard
  {
    question: 'Wann wurde die Deutsche Bundesbank gegründet?',
    options: ['1948', '1951', '1957', '1960'],
    correctAnswer: 2,
    category: 'Wirtschaft',
    difficulty: 'hard',
  },
  {
    question: 'Was ist der MDAX?',
    options: ['Mid-Cap-Index', 'Monopol-Index', 'Mittelstands-Index', 'Medien-Index'],
    correctAnswer: 0,
    category: 'Wirtschaft',
    difficulty: 'hard',
  },
  {
    question: 'Wie viele Mitarbeiter hat Volkswagen weltweit ca.?',
    options: ['300.000', '500.000', '670.000', '800.000'],
    correctAnswer: 2,
    category: 'Wirtschaft',
    difficulty: 'hard',
  },
  {
    question: 'Wann ging SAP an die Börse?',
    options: ['1988', '1990', '1992', '1995'],
    correctAnswer: 0,
    category: 'Wirtschaft',
    difficulty: 'hard',
  },
  {
    question: 'Was ist das größte deutsche Familienunternehmen?',
    options: ['Aldi', 'BMW', 'Bosch', 'Bertelsmann'],
    correctAnswer: 2,
    category: 'Wirtschaft',
    difficulty: 'hard',
  },

  // Weitere gemischte Fragen für Vielfalt
  {
    question: 'Welches Bundesland grenzt nicht an ein anderes Land?',
    options: ['Saarland', 'Sachsen', 'Thüringen', 'Hessen'],
    correctAnswer: 3,
    category: 'Geografie',
    difficulty: 'medium',
  },
  {
    question: 'Wie viele Menschen leben ca. in Deutschland?',
    options: ['70 Mio', '80 Mio', '84 Mio', '90 Mio'],
    correctAnswer: 2,
    category: 'Geografie',
    difficulty: 'easy',
  },
  {
    question: 'Welche Stadt ist keine Landeshauptstadt?',
    options: ['Dresden', 'Erfurt', 'Frankfurt', 'Düsseldorf'],
    correctAnswer: 2,
    category: 'Geografie',
    difficulty: 'medium',
  },
  {
    question: 'Wo liegt das Berchtesgadener Land?',
    options: ['Bayern', 'Hessen', 'Thüringen', 'Sachsen'],
    correctAnswer: 0,
    category: 'Geografie',
    difficulty: 'medium',
  },
  {
    question: 'Welcher Fluss fließt durch Dresden?',
    options: ['Rhein', 'Elbe', 'Donau', 'Main'],
    correctAnswer: 1,
    category: 'Geografie',
    difficulty: 'easy',
  },
  {
    question: 'Wie heißt die Hauptstadt von Schleswig-Holstein?',
    options: ['Lübeck', 'Kiel', 'Flensburg', 'Hamburg'],
    correctAnswer: 1,
    category: 'Geografie',
    difficulty: 'medium',
  },
  {
    question: 'Welche Insel gehört zu Deutschland?',
    options: ['Korsika', 'Sylt', 'Malta', 'Kreta'],
    correctAnswer: 1,
    category: 'Geografie',
    difficulty: 'easy',
  },
  {
    question: 'Was ist die Zugspitze?',
    options: ['Fluss', 'Berg', 'Stadt', 'See'],
    correctAnswer: 1,
    category: 'Geografie',
    difficulty: 'easy',
  },
  {
    question: 'Wo liegt der Nationalpark Harz?',
    options: ['Bayern', 'Sachsen-Anhalt', 'Hessen', 'Baden-Württemberg'],
    correctAnswer: 1,
    category: 'Geografie',
    difficulty: 'medium',
  },
  {
    question: 'Welches Bundesland hat Bremen als Hauptstadt?',
    options: ['Niedersachsen', 'Bremen', 'Hamburg', 'Schleswig-Holstein'],
    correctAnswer: 1,
    category: 'Geografie',
    difficulty: 'easy',
  },

  {
    question: 'Wer war der erste deutsche im All?',
    options: ['Sigmund Jähn', 'Ulf Merbold', 'Thomas Reiter', 'Alexander Gerst'],
    correctAnswer: 0,
    category: 'Geschichte',
    difficulty: 'medium',
  },
  {
    question: 'Wann wurde Berlin wieder Hauptstadt?',
    options: ['1989', '1990', '1991', '1999'],
    correctAnswer: 3,
    category: 'Geschichte',
    difficulty: 'medium',
  },
  {
    question: 'Wer war erster Bundespräsident nach der Wende?',
    options: ['Richard von Weizsäcker', 'Roman Herzog', 'Johannes Rau', 'Horst Köhler'],
    correctAnswer: 0,
    category: 'Geschichte',
    difficulty: 'medium',
  },
  {
    question: 'Wann trat der Grundlagenvertrag in Kraft?',
    options: ['1970', '1971', '1972', '1973'],
    correctAnswer: 3,
    category: 'Geschichte',
    difficulty: 'hard',
  },
  {
    question: 'Wer war der letzte DDR-Ministerpräsident?',
    options: ['Erich Honecker', 'Hans Modrow', 'Lothar de Maizière', 'Egon Krenz'],
    correctAnswer: 2,
    category: 'Geschichte',
    difficulty: 'hard',
  },

  {
    question: 'Welcher Komponist wurde in Bonn geboren?',
    options: ['Mozart', 'Bach', 'Beethoven', 'Brahms'],
    correctAnswer: 2,
    category: 'Kultur',
    difficulty: 'medium',
  },
  {
    question: 'Wer schrieb "Die Blechtrommel"?',
    options: ['Günter Grass', 'Heinrich Böll', 'Thomas Mann', 'Hermann Hesse'],
    correctAnswer: 0,
    category: 'Kultur',
    difficulty: 'medium',
  },
  {
    question: 'Was ist das Reichstagsgebäude heute?',
    options: ['Museum', 'Bundestag', 'Rathaus', 'Gericht'],
    correctAnswer: 1,
    category: 'Kultur',
    difficulty: 'easy',
  },
  {
    question: 'Wo steht die Frauenkirche?',
    options: ['München', 'Dresden', 'Berlin', 'Both A and B'],
    correctAnswer: 3,
    category: 'Kultur',
    difficulty: 'medium',
  },
  {
    question: 'Welches Fest wird in Köln gefeiert?',
    options: ['Oktoberfest', 'Karneval', 'Cannstatter Wasen', 'Schützenfest'],
    correctAnswer: 1,
    category: 'Kultur',
    difficulty: 'easy',
  },

  {
    question: 'Wer ist aktueller Bundespräsident (2026)?',
    options: ['Frank-Walter Steinmeier', 'Joachim Gauck', 'Christian Wulff', 'Horst Köhler'],
    correctAnswer: 0,
    category: 'Politik',
    difficulty: 'easy',
  },
  {
    question: 'Wie heißt die zweite Kammer des Parlaments?',
    options: ['Bundestag', 'Bundesrat', 'Landtag', 'Bundesversammlung'],
    correctAnswer: 1,
    category: 'Politik',
    difficulty: 'easy',
  },
  {
    question: 'Was steht in Artikel 1 des Grundgesetzes?',
    options: ['Meinungsfreiheit', 'Menschenwürde', 'Gleichheit', 'Demokratie'],
    correctAnswer: 1,
    category: 'Politik',
    difficulty: 'easy',
  },
  {
    question: 'Wie viele Ministerien gibt es ca. auf Bundesebene?',
    options: ['10', '15', '20', '25'],
    correctAnswer: 1,
    category: 'Politik',
    difficulty: 'medium',
  },
  {
    question: 'Wer kann Gesetze vorschlagen?',
    options: ['Bundestag', 'Bundesrat', 'Bundesregierung', 'Alle'],
    correctAnswer: 3,
    category: 'Politik',
    difficulty: 'medium',
  },

  {
    question: 'Wo fand die Fußball-WM 2006 statt?',
    options: ['Frankreich', 'Deutschland', 'Italien', 'Brasilien'],
    correctAnswer: 1,
    category: 'Sport',
    difficulty: 'easy',
  },
  {
    question: 'Welches Team gewann 1990 die Formel 1?',
    options: ['Ferrari', 'McLaren', 'Williams', 'Benetton'],
    correctAnswer: 1,
    category: 'Sport',
    difficulty: 'hard',
  },
  {
    question: 'Wer trainiert aktuell die Nationalmannschaft?',
    options: ['Jogi Löw', 'Hansi Flick', 'Julian Nagelsmann', 'Thomas Tuchel'],
    correctAnswer: 2,
    category: 'Sport',
    difficulty: 'easy',
  },
  {
    question: 'Welcher deutsche Spieler spielte für Real Madrid?',
    options: ['Toni Kroos', 'Mesut Özil', 'Sami Khedira', 'Alle'],
    correctAnswer: 3,
    category: 'Sport',
    difficulty: 'medium',
  },
  {
    question: 'Wie heißt das Stadion in Dortmund?',
    options: ['Signal Iduna Park', 'Allianz Arena', 'Red Bull Arena', 'Mercedes-Benz Arena'],
    correctAnswer: 0,
    category: 'Sport',
    difficulty: 'easy',
  },

  {
    question: 'Was produziert Bayer?',
    options: ['Autos', 'Pharma', 'Möbel', 'Kleidung'],
    correctAnswer: 1,
    category: 'Wirtschaft',
    difficulty: 'easy',
  },
  {
    question: 'Wo hat Audi seinen Sitz?',
    options: ['München', 'Stuttgart', 'Ingolstadt', 'Wolfsburg'],
    correctAnswer: 2,
    category: 'Wirtschaft',
    difficulty: 'medium',
  },
  {
    question: 'Was ist Lidl?',
    options: ['Bank', 'Discounter', 'Autohaus', 'Restaurant'],
    correctAnswer: 1,
    category: 'Wirtschaft',
    difficulty: 'easy',
  },
  {
    question: 'Welche Firma produziert Windows nicht?',
    options: ['Microsoft', 'SAP', 'Google', 'Alle'],
    correctAnswer: 3,
    category: 'Wirtschaft',
    difficulty: 'easy',
  },
  {
    question: 'Was bedeutet AG?',
    options: ['Aktiengesellschaft', 'Allgemeine Gruppe', 'Arbeiter Gemeinschaft', 'Auto Garage'],
    correctAnswer: 0,
    category: 'Wirtschaft',
    difficulty: 'easy',
  },
];

// Hilfsfunktion: Zufällige Fragen auswählen
export const getRandomQuestions = (count: number): QuizQuestion[] => {
  const shuffled = [...deutschlandQuestions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
};

// Hilfsfunktion: Fragen nach Kategorie
export const getQuestionsByCategory = (category: QuizQuestion['category']): QuizQuestion[] => {
  return deutschlandQuestions.filter((q) => q.category === category);
};

// Hilfsfunktion: Fragen nach Schwierigkeit
export const getQuestionsByDifficulty = (
  difficulty: QuizQuestion['difficulty']
): QuizQuestion[] => {
  return deutschlandQuestions.filter((q) => q.difficulty === difficulty);
};
